SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `Prueba` ;


-- -----------------------------------------------------
-- Table `Prueba`.`ROL_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prueba`.`ROL_Usuario` (
  `ROL_ROL` VARCHAR(30) NOT NULL,
  `Usuario_USUARIO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ROL_ROL`, `Usuario_USUARIO`),
  INDEX `fk_ROL_has_Usuario_Usuario1_idx` (`Usuario_USUARIO` ASC),
  INDEX `fk_ROL_has_Usuario_ROL_idx` (`ROL_ROL` ASC),
  CONSTRAINT `fk_ROL_has_Usuario_ROL`
    FOREIGN KEY (`ROL_ROL`)
    REFERENCES `Prueba`.`ROL` (`ROL`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ROL_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_USUARIO`)
    REFERENCES `Prueba`.`Usuario` (`USUARIO`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
